import { Cars as CarsModel } from "../cars/cars.types";

type Cars = Omit<CarsModel, 'id' | 'created_at' | 'updated_at'>;

const carsInfo: any = [
  {
    car_name: 'Ford Fusion',
    type: 'Sedan',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178938/samples/CARS_IMG/5_z0krxi.png',
    seats: 5,
    luggage: 2,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v58000auli6da0ozzoj',
  },
  {
    car_name: 'Suzuki Vitara',
    type: 'SUV',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178938/samples/CARS_IMG/6_nnmq28.png',
    seats: 5,
    luggage: 2,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v58000duli6izqk40ue',
  },
  {
    car_name: 'Volkswagen Up',
    type: 'Hatchback',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178938/samples/CARS_IMG/7_wedwp1.png',
    seats: 5,
    luggage: 2,
    air_conditioner: false,
    transmition: 'MANUAL',
    fare_km: 2500,
    driver_id: 'cllzw3v580015uli6p6lgq9m0',
  },
  {
    car_name: 'Honda Accord',
    type: 'Sedan',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178938/samples/CARS_IMG/8_uxyjvv.png',
    seats: 5,
    luggage: 2,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v58000vuli6k3dcr3lj',
  },
  {
    car_name: 'Force Traveller',
    type: 'Camper',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178938/samples/CARS_IMG/9_dxlinv.png',
    seats: 9,
    luggage: 4,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v570002uli6xix62s0i',
  },
  {
    car_name: 'Land Rove Evoque',
    type: 'SUV',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178938/samples/CARS_IMG/10_uangsi.png',
    seats: 5,
    luggage: 4,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v580012uli64qij3ava',
  },
  {
    car_name: 'BMW i8 2018',
    type: 'Luxury Coupe',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178939/samples/CARS_IMG/11_ykvsdd.png',
    seats: 2,
    luggage: 2,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v580014uli6bh73yfty',
  },
  {
    car_name: 'Tesla Model 3',
    type: 'Electric Sedan',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178939/samples/CARS_IMG/12_xkpmuq.png',
    seats: 5,
    luggage: 2,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v58000zuli6ed3ogd3n',
  },
  {
    car_name: 'BMW i4',
    type: 'Electric Sedan',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178939/samples/CARS_IMG/13_vjncrn.png',
    seats: 5,
    luggage: 2,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v580004uli66m7fsq8a',
  },
  {
    car_name: 'Renault Kwid',
    type: 'Hatchback',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178939/samples/CARS_IMG/14_mky2kd.png',
    seats: 5,
    luggage: 1,
    air_conditioner: true,
    transmition: 'MANUAL',
    fare_km: 2500,
    driver_id: 'cllzw3v58000fuli6mepi4r21',
  },
  {
    car_name: 'Seat Leon',
    type: 'Hatchback',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178939/samples/CARS_IMG/15_vlcxkp.png',
    seats: 5,
    luggage: 1,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v580005uli6yr87gl8g',
  },
  {
    car_name: 'Volkswagen Transporter',
    type: 'Van',
    img: 'https://res.cloudinary.com/dbmertsgv/image/upload/v1693178939/samples/CARS_IMG/16_anuzjv.png',
    seats: 9,
    luggage: 4,
    air_conditioner: true,
    transmition: 'AUTOMATIC',
    fare_km: 2500,
    driver_id: 'cllzw3v580009uli62i5um5o2',
  },
]

export const carsSeeder: Cars[] = Array.from({ length: carsInfo.length }).map((e, i) => {
  return ({
    car_name: carsInfo[i].car_name,
    type: carsInfo[i].type,
    img: carsInfo[i].img,
    seats: carsInfo[i].seats,
    luggage: carsInfo[i].luggage,
    air_conditioner: carsInfo[i].air_conditioner,
    transmition: carsInfo[i].transmition,
    fare_km: carsInfo[i].fare_km,
    driver_id: carsInfo[i].driver_id,
  })
});
